// Indicator implementations. Each function returns an array of values aligned to input data. // Each function computes value for index i using only data[0..i] (no look-ahead). // Data expected: array of objects {close: Number, high, low, open, volume, date}

export function SMA(values, period) { const out = new Array(values.length).fill(null); let sum = 0; for (let i = 0; i < values.length; i++) { sum += values[i]; if (i >= period) sum -= values[i - period]; if (i >= period - 1) out[i] = sum / period; } return out; }

export function EMA(values, period) { const out = new Array(values.length).fill(null); const k = 2 / (period + 1); let prev = null; for (let i = 0; i < values.length; i++) { const v = values[i]; if (i === period - 1) { // Start EMA with SMA of first period let sum = 0; for (let j = 0; j < period; j++) sum += values[j]; prev = sum / period; out[i] = prev; } else if (i >= period) { prev = v * k + prev * (1 - k); out[i] = prev; } } return out; }

export function RSI(values, period = 14) { const out = new Array(values.length).fill(null); let gains = 0, losses = 0; for (let i = 1; i < values.length; i++) { const diff = values[i] - values[i - 1]; if (i <= period) { if (diff > 0) gains += diff; else losses += Math.abs(diff); if (i === period) { let avgGain = gains / period; let avgLoss = losses / period; out[i] = avgLoss === 0 ? 100 : 100 - (100 / (1 + avgGain / avgLoss)); var prevGain = avgGain; var prevLoss = avgLoss; } } else { const gain = diff > 0 ? diff : 0; const loss = diff < 0 ? Math.abs(diff) : 0; prevGain = (prevGain * (period - 1) + gain) / period; prevLoss = (prevLoss * (period - 1) + loss) / period; out[i] = prevLoss === 0 ? 100 : 100 - (100 / (1 + prevGain / prevLoss)); } } return out; }

export function MACD(values, fast = 12, slow = 26, signal = 9) { const emaFast = EMA(values, fast); const emaSlow = EMA(values, slow); const macd = new Array(values.length).fill(null); for (let i = 0; i < values.length; i++) { if (emaFast[i] != null && emaSlow[i] != null) macd[i] = emaFast[i] - emaSlow[i]; } const signalLine = EMA(macd.map((v) => (v == null ? 0 : v)), signal); return { series: macd, signal: signalLine, meta: { type: "hist", label: "MACD" } }; }

export function BollingerBands(values, period = 20, stdDev = 2) { const middle = SMA(values, period); const outUpper = new Array(values.length).fill(null); const outLower = new Array(values.length).fill(null); for (let i = period - 1; i < values.length; i++) { let sum = 0; for (let j = i - period + 1; j <= i; j++) { const diff = values[j] - middle[i]; sum += diff * diff; } const variance = sum / period; const sd = Math.sqrt(variance); outUpper[i] = middle[i] + sd * stdDev; outLower[i] = middle[i] - sd * stdDev; } // return main series as middle (so comparisons like ">" work), but also include upper/lower return { series: middle, upper: outUpper, lower: outLower, meta: { type: "bb", label: BB ${period} } }; }

// Helper to pick indicator arrays from data by indicator name like "SMA-20", "EMA-50", "RSI-14", "MACD", "BB-20" export function computeIndicatorByName(data, name) { const closes = data.map((d) => d.close); if (name.startsWith("SMA")) { const p = parseInt(name.split("-")[1], 10) || 20; return { series: SMA(closes, p), meta: { type: "line", label: SMA ${p} } }; } if (name.startsWith("EMA")) { const p = parseInt(name.split("-")[1], 10) || 20; return { series: EMA(closes, p), meta: { type: "line", label: EMA ${p} } }; } if (name.startsWith("RSI")) { const p = parseInt(name.split("-")[1], 10) || 14; return { series: RSI(closes, p), meta: { type: "osc", label: RSI ${p} } }; } if (name === "MACD") { return MACD(closes, 12, 26, 9); } if (name.startsWith("BB")) { const p = parseInt(name.split("-")[1], 10) || 20; return BollingerBands(closes, p, 2); } return { series: [] }; }
